def generate_report_summary(fields: dict, language: str):
    name = fields.get("NAME", "Not Mentioned")
    date = fields.get("DATE", "N/A")
    time = fields.get("TIME", "N/A")
    place = fields.get("INCIDENT_PLACE", "Not Mentioned")
    complaint = fields.get("COMPLAINT_TYPE", "General Complaint")

    if language == "hi":
        return (
            f"यह पुलिस शिकायत रिपोर्ट दिनांक {date} को समय {time} पर दर्ज की गई। "
            f"शिकायतकर्ता {name} द्वारा {place} क्षेत्र में "
            f"{complaint} से संबंधित शिकायत दर्ज कराई गई है।"
        )

    elif language == "en":
        return (
            f"This police complaint report was registered on {date} at {time}. "
            f"The complainant, {name}, reported a case of "
            f"{complaint} at/near the {place}."
        )

    else:  # auto / hinglish
        return (
            f"Yeh complaint {date} ko {time} par register hui hai. "
            f"Complainant {name} ne {place} area mein "
            f"{complaint} se related report file ki hai."
        )
def generate_final_report(
    fields: dict,
    summary: str,
    final_text,
    input_language: str,
    audio_evidence_id
):
    date = fields.get("DATE", "N/A")

    # =============================
    # HINDI REPORT
    # =============================
    if input_language == "hi":
        return f"""
==================================================
            पुलिस शिकायत रिपोर्ट
==================================================
ऑडियो साक्ष्य आईडी : {audio_evidence_id}
इनपुट भाषा        : हिंदी
AI पुष्टि ऑडियो     : उपयोग किया गया
स्थिति            : User-Edited & Confirmed

--------------------------------------------------
1. रिपोर्ट सारांश
--------------------------------------------------
{summary}

--------------------------------------------------
2. शिकायत का विस्तृत विवरण
--------------------------------------------------
{final_text}

--------------------------------------------------
तैयार किया गया : Voice-Based FIR System
दिनांक : {date}
==================================================
"""

    # =============================
    # ENGLISH REPORT
    # =============================
    else:
        return f"""
==================================================
            POLICE COMPLAINT REPORT
==================================================
Audio Evidence ID : {audio_evidence_id}
Input Language    : English
AI Confirmation  : Used
Status           : User-Edited & Confirmed

--------------------------------------------------
1. REPORT SUMMARY
--------------------------------------------------
{summary}

--------------------------------------------------
2. DETAILED COMPLAINT DESCRIPTION
--------------------------------------------------
{final_text}

--------------------------------------------------
Generated By : Voice-Based FIR System
Date : {date}
==================================================
"""
