def generate_report_summary(fields: dict, language: str):
    if language == "hi":
        return (
            f"यह रिपोर्ट {fields['DATE']} को {fields['TIME']} बजे दर्ज की गई है। "
            f"शिकायतकर्ता {fields['NAME']} द्वारा "
            f"{fields['INCIDENT_PLACE']} क्षेत्र में "
            f"{fields['COMPLAINT_TYPE']} से संबंधित शिकायत दर्ज की गई है।"
        )
    else:
        return (
            f"This report was generated on {fields['DATE']} at {fields['TIME']}. "
            f"The complainant {fields['NAME']} reported a "
            f"{fields['COMPLAINT_TYPE']} near {fields['INCIDENT_PLACE']}."
        )

def generate_final_report(
    fields: dict,
    summary: str,
    report_language: str,
    hindi_text: str,
    english_text: str,
    # audio_evidence_id: str,
    input_language: str
):
    if report_language == "hi":
        return f"""
==================================================
            पुलिस शिकायत रिपोर्ट
==================================================
ऑडियो साक्ष्य आईडी : {1}
इनपुट भाषा        : {input_language}
AI पुष्टि ऑडियो     : उपयोग किया गया
स्थिति            : User-Edited & Confirmed

--------------------------------------------------
1. रिपोर्ट सारांश
--------------------------------------------------
{summary}

--------------------------------------------------
2. शिकायत विवरण (हिंदी)
--------------------------------------------------
{hindi_text}

--------------------------------------------------
तैयार किया गया : Voice-Based FIR System
--------------------------------------------------
"""
    else:
        return f"""
==================================================
            POLICE COMPLAINT REPORT
==================================================
Audio Evidence ID : {1}
Input Language    : {input_language}
AI Confirmation  : Used
Status           : User-Edited & Confirmed

--------------------------------------------------
1. REPORT SUMMARY
--------------------------------------------------
{summary}

--------------------------------------------------
2. COMPLAINT DESCRIPTION (ENGLISH)
--------------------------------------------------
{english_text}

--------------------------------------------------
Generated By : Voice-Based FIR System
--------------------------------------------------
"""
