import os
import re
from datetime import datetime
import whisper
from gtts import gTTS
from playsound import playsound
import streamlit as st
from model import load_model


AI_VOICE_FILE = "ai_confirm.mp3"    # AI confirmation audio

def generate_audio_evidence_id():
    now = datetime.now()
    return f"AE-{now.strftime('%Y%m%d-%H%M%S')}" 

AUDIO_EVIDENCE_ID = generate_audio_evidence_id()

@st.cache_resource
def get_model(model_name="small"):
    return load_model(model_name)

model = load_model()
def transcribe_pipline(AUDIO_FILE):
    result = model.transcribe(
        AUDIO_FILE,
        fp16=False,
        temperature=0
    )
    input_language = result.get("language", "unknown")
    original_text = result["text"].strip()
    return original_text, input_language

# def generate_ai_confirmation(text, lang):
#     tts_lang = lang if lang in ["hi", "en"] else "hi"
#     tts = gTTS(text=text, lang=tts_lang)
#     tts.save(AI_VOICE_FILE)
#     return AI_VOICE_FILE

def confirmed_audio_to_text(AUDIO_FILE):
    hi = model.transcribe(AUDIO_FILE, language="hi", fp16=False)["text"]
    en = model.transcribe(AUDIO_FILE, task="translate", language="en", fp16=False)["text"]
    
    return {
        "hindi": hi.strip(),
        "english": en.strip()
    }


# # ==================================================
# # 6️⃣ USER CHOICE FOR REPORT LANGUAGE (UNCHANGED)
# # ==================================================
# print("\n📘 Report language choose kare:")
# print("👉 Hindi ke liye: hi")
# print("👉 English ke liye: en")

# choice = input("Your choice (hi/en): ").strip().lower()

# # ==================================================
# # 7️⃣ REPORT SUMMARY (UNCHANGED)
# # ==================================================
# if choice == "hi":
#     summary = (
#         f"यह रिपोर्ट {fields['DATE']} को {fields['TIME']} बजे दर्ज की गई है। "
#         f"शिकायतकर्ता {fields['NAME']} द्वारा "
#         f"{fields['INCIDENT_PLACE']} क्षेत्र में "
#         f"{fields['COMPLAINT_TYPE']} से संबंधित शिकायत दर्ज की गई है।"
#     )
# else:
#     summary = (
#         f"This report was generated on {fields['DATE']} at {fields['TIME']}. "
#         f"The complainant {fields['NAME']} reported a "
#         f"{fields['COMPLAINT_TYPE']} near {fields['INCIDENT_PLACE']}."
#     )

# # ==================================================
# # 8️⃣ FINAL REPORT (WITH AUDIO EVIDENCE ID)
# # ==================================================
# if choice == "hi":
#     report = f"""
# ==================================================
#             पुलिस शिकायत रिपोर्ट
# ==================================================
# ऑडियो साक्ष्य आईडी : {AUDIO_EVIDENCE_ID}
# इनपुट भाषा        : {input_language}
# AI पुष्टि ऑडियो     : उपयोग किया गया
# स्थिति            : User‑Edited & Confirmed

# --------------------------------------------------
# 1. रिपोर्ट सारांश
# --------------------------------------------------
# {summary}

# --------------------------------------------------
# 2. शिकायत विवरण (हिंदी)
# --------------------------------------------------
# {hindi_text}

# --------------------------------------------------
# तैयार किया गया : Voice-Based FIR System
# --------------------------------------------------
# """
# else:
#     report = f"""
# ==================================================
#             POLICE COMPLAINT REPORT
# ==================================================
# Audio Evidence ID : {AUDIO_EVIDENCE_ID}
# Input Language    : {input_language}
# AI Confirmation  : Used
# Status           : User‑Edited & Confirmed

# --------------------------------------------------
# 1. REPORT SUMMARY
# --------------------------------------------------
# {summary}

# --------------------------------------------------
# 2. COMPLAINT DESCRIPTION (ENGLISH)
# --------------------------------------------------
# {english_text}

# --------------------------------------------------
# Generated By : Voice-Based FIR System
# --------------------------------------------------
# """

# with open(REPORT_FILE, "w", encoding="utf-8") as f:
#     f.write(report)

# print("\n📄 FINAL REPORT GENERATED → final_report.txt")
# print("🎉 DONE — REPORT EDIT + AUDIO EVIDENCE ID ADDED")